name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger when main branch is updated

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Prepare public folder
      run: |
        mkdir public
        cp index.html public/
        cp times.json public/
        cp LiquidCrystal.otf public/
      shell: bash

    - name: Deploy to gh-pages → AdiZero/
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        destination_dir: AdiZero
